#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $JOOMLA_USER WITH PASSWORD '$JOOMLA_PASSWORD';
	CREATE DATABASE $JOOMLA_DB;
	GRANT ALL PRIVILEGES ON DATABASE $JOOMLA_DB TO $JOOMLA_USER;
	ALTER DATABASE $JOOMLA_DB OWNER TO $JOOMLA_USER;
EOSQL

