services:
    postgresql:
        image: postgres:latest
        hostname: postgres.local
        restart: always
        shm_size: 128mb
        env_file: ~/docker_data/postgres/postgres.env
        volumes:
            - postgres_data:/var/lib/postgresql/data/

    adminer:
        image: adminer:latest
        restart: no
        depends_on:
            - postgresql
        ports:
            - 17080:8080

    cscs-test:
        image: cgs/cscs:latest
        build: .
        hostname: test.cscs.local
        restart: always
        depends_on:
            - postgresql
        volumes:
            - ~/docker_data/cscs-test/application.properties:/application.properties
            - cscs_test_data:/Data

    cscs:
        image: cgs/cscs:latest
        build: .
        hostname: cscs.local
        restart: always
        depends_on:
            - postgresql
        volumes:
            - ~/docker_data/cscs/application.properties:/application.properties
            - cscs_data:/Data

    mariadb:
        image: mariadb:latest
        hostname: mariadb.local
        restart: unless-stopped
        env_file: ~/docker_data/mariadb/mariadb.env
        volumes:
          - mariadb_data:/var/lib/mysql

    joomla:
        image: joomla:latest
        hostname: joomla.local
        restart: always
        env_file: ~/docker_data/joomla/joomla.env
        volumes:
          - joomla_data:/var/www/html
    
    portainer:
        image: portainer/portainer-ce:latest
        hostname: portainer.local
        restart: always
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data

    watchtower:
        image: containrrr/watchtower:latest
        restart: always
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        env_file: ~/docker_data/watchtower/notifications.env
        environment:
          - WATCHTOWER_CLEANUP=true
          - WATCHTOWER_SCHEDULE=0 0 3 * * *
          - WATCHTOWER_DISABLE_CONTAINERS=cscsystem-cscs-1
            # Every Day 3:00 in the night
    
    borgmatic:
        image: ghcr.io/borgmatic-collective/borgmatic:latest
        restart: always
        env_file: ~/docker_data/borgmatic/borgmatic.env
        volumes:
          - ~/borg:/mnt/borg-repository
          - ~/docker_data/borgmatic/etc:/etc/borgmatic.d/
          - ~/docker_data/borgmatic/config:/root/.config/borg
          - ~/docker_data/borgmatic/config:/root/.cache/borg
          # Data to Backup 
          - joomla_data:/mnt/src/joomla_data/
          - cscs_data:/mnt/src/cscs_data/
          - mariadb_data:/mnt/src/mariadb_data/
          - portainer_data:/mnt/src/portainer_data/
          - postgres_data:/mnt/src/postgres_data/
          - ~/docker_data/:/mnt/src/docker_data/
          - caddy_data:/mnt/src/caddy_data/

    caddy:
      image: caddy
      restart: always
      ports:
        - 80:80
        - 443:443
      volumes:
        - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
        - caddy_data:/data

volumes:
    joomla_data:
    portainer_data:
    postgres_data:
    cscs_data:
    mariadb_data:
    caddy_data:
    cscs_test_data:
