server {
    listen 80;
    listen [::]:80;

    server_name *.code-green-systems.de code-green-systems.de;
    server_tokens off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    if ($scheme = "http") {
        return 301 https://$host$request_uri;
    }
}
