upstream portainer_code-green-systems.de {
    server portainer.local:9000;
}

server {

    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    
    server_name portainer.code-green-systems.de;
    
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    
    ssl_certificate /etc/nginx/ssl/live/portainer.code-green-systems.de/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/live/portainer.code-green-systems.de/privkey.pem;
    
    location / {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        proxy_cache_valid 200 302 1m;
        proxy_pass http://portainer_code-green-systems.de;
    }
}
