on:
  push:
    branches:
      #- develop
      #- main
      - github-actions

jobs:
  deploy:
    runs-on: self-hosted 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: compile
        run: ./mvnw -Pproduction clean package
      
      - name: build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: cgs/cscs:latest
      - name: update production
        run: |
          docker run -d \
            --name cscs-updater \
            -v /var/run/docker.sock:/var/run/docker.sock \
            containrrr/watchtower --run-once cscsystem-cscs-1
